jobs/docker/templates/bin/docker_ctl

Solve unmount issue when undeploying/updating docker jobs.
The bosh/monit kill routine will kill a docker daemon if it doesn't stop within the set grace period. This routine has no knowledge about the containers, so if the docker daemon doesn't respond fast enough, this will lead to the unmount issue.
Better let the daemon kill its containers. It will first issue SIGTERM and then SIGKILL, but it will remain in control of the shutdown process for the containers. Only then stop the docker daemon.
* Stop all running containers before stopping the docker daemon
* Remove former unmount hack
Deploy broker, create non-trivial service instance (e.g. redis), check that a corresponding docker container was started, undeploy broker. Before this PR, undeploy (or update) failed with ```umount: …
```

Replace unmount hack w/ container stop loop to properly shutdown daemon

---

.gitmodules
examples/docker-broker-aws.yml
examples/docker-broker-bosh-lite.yml
examples/docker-broker-google.yml
examples/docker-broker-openstack.yml
jobs/broker-deregistrar
jobs/broker-registrar
jobs/cf-containers-broker/spec
jobs/cf-containers-broker/templates/bin/job_properties.sh.erb
jobs/cf-containers-broker/templates/config/logrotate.conf.erb
jobs/cf-containers-broker/templates/config/logrotate.cron.erb
jobs/cf-containers-broker/templates/config/settings.yml.erb
jobs/cf-containers-broker/templates/config/unicorn.conf.rb.erb
packages/broker-registrar

Simplify registration of the broker at the CF CC.
The current release requires manual (or otherwise automated) registration of the broker at the CF CC. There is however a Pivotal broker-registrar that would be handy to use instead.
Integrate https://github.com/pivotal-cf/broker-registrar.
* Add new submodule with the Pivotal broker-registrar
* Add jobs for registration and deregistration to all deployment samples
* Add missing properties and rename former ```cfcontainersbroker``` properties into ```broker```
The Pivotal broker-registrar properties overlap significantly with the docker-boshrelease properties. Unfortunately they are called differently. To avoid property duplicates defining the same data, this change renames all ```cfcontainersbroker``` properties into ```broker``` (as they …

Integrate Pivotal broker-registrar

---

config/blobs.yml
config/final.yml

Newest bosh_cli doesn't support blob encryption anymore. To make this boshrelease compatible I have re-uploaded the blobs unencrypted.
closes #52

Decrypt BOSH Release

---

jobs/cf-containers-broker/spec
jobs/cf-containers-broker/templates/bin/cf-containers-broker_ctl
jobs/cf-containers-broker/templates/bin/job_properties.sh.erb

Enable automatic restart of containers with newest image/configuration when job cf-containers-broker is restarted.
See the [cf-containers-broker README](https://github.com/cloudfoundry-community/cf-containers-broker#updating-containers) for details.

Update cf containers broker

---

jobs/docker/templates/bin/docker_ctl
packages/docker/packaging
packages/docker/spec

Signed-off-by: Satheesh Uppalapati <Satheesh.Uppalapati@allstate.com>
This PR addresses bug #56. To make a release of it we would need to get `docker/docker-1.11.0.tgz` blob sync. 
*Linux 64bit tgz*: https://get.docker.com/builds/Linux/x86_64/docker-1.11.0.tgz

Upgrades docker to version 1.11.0

---

jobs/flannel/spec
jobs/flannel/templates/bin/ctl

* Expose flannel subnet range as `flannel.ip-range`
* Use `curl` instead of `etcdctl`; etcd may live on separate host
WDYT @lnguyen?

Make flannel subnet configurable.

---

CONTAINERS.md
jobs/containers/spec
jobs/containers/templates/bin/containers_ctl.erb
jobs/containers/templates/bin/job_properties.sh.erb
jobs/flannel/spec

This makes it much simpler to, e.g., pass JSON in through an environment variable, since it avoids multiple layers of shell-escaping that would be needed with --env/env_vars. Here's the [docker run doc for --env-file](https://docs.docker.com/engine/reference/commandline/run/#/set-environment-variables--e---env---env-file).

Add property for --env-file option to docker run.

---

jobs/docker/spec
jobs/docker/templates/bin/ctl
jobs/docker/templates/bin/job_properties.sh.erb

Allowing an operator to explicitly set the bridge IP, which is
passed to the docker daemon via the '--bip' flag, is useful when
the IP of the docker0 NIC needs to be customized.
Example: when deploying Kubernetes with CNI, and a Flannel overlay, the
docker0 NIC (and associated route) must not conflict with CNI.
Signed-off-by: Josh Winters <jwinters@pivotal.io>

Externalizing the Docker bridge IP as a BOSH property.

---

jobs/containers/monit
jobs/docker/templates/bin/job_properties.sh.erb

I have reverted back below commit and tested changes with bosh director 1.3262.23.0 and with the latest version. It works fine.
https://github.com/cloudfoundry-community/docker-boshrelease/commit/ed6fb072bc81470491bb07b16f2614498367a41a

using %> instead of -%> for fix for bosh director 1.3262.23.0

---

jobs/containers/spec
jobs/containers/templates/bin/job_properties.sh.erb

When specifying one these options the release breaks:
* dns
* dns_options
* dns_search
This PR fixes the comment headers in the job properties as well as few spelling mistakes in the job spec.

Fix dns options for containers job

---

jobs/docker/spec
jobs/docker/templates/bin/ctl
jobs/docker/templates/bin/job_properties.sh.erb

Some images (such as ElasticSearch) require `vm.max_map_count` to be set higher than normal defaults.
(not sure if this is the best way to do this, but it seemed to work for us)

Allow config of vm.max_map_count

---

jobs/cf-containers-broker/templates/bin/job_properties.sh.erb
jobs/containers/spec
jobs/containers/templates/bin/job_properties.sh.erb
jobs/docker/spec
jobs/docker/templates/bin/job_properties.sh.erb
jobs/swarm-agent/templates/bin/job_properties.sh.erb
jobs/swarm-manager/templates/bin/job_properties.sh.erb
src/bosh-helpers/ctl_setup.sh

* Expose store_dir in spec for docker and containers
* Remove STORE_DIR exports from other job_properties as they were not used anywhere
Signed-off-by: Morena De Liddo <mdeliddo@pivotal.io>

Make STORE_DIR configurable

---

ci/release_notes.md
jobs/docker/spec
jobs/docker/templates/bin/job_properties.sh.erb
jobs/docker/templates/config/docker.cacert.erb
jobs/docker/templates/config/docker.cert.erb
jobs/docker/templates/config/docker.key.erb
manifests/op-disable-remote-docker-access.yml

@damaru-inc look good for you? Just set `docker.tcp_address` to 127.0.0.1 (the default) and TLS certs won't be required.
See https://github.com/cloudfoundry-community/docker-boshrelease/commit/0f8c49204f926cd300ac7c59c305dfbf4e2eb324#commitcomment-25484535

Allow disable remote docker access (and requirement for TLS certs)

---

jobs/containers/monit
jobs/containers/spec

The default Monit timeout is 30s, and since some images may depend on others, this timeout may not be enough.

Allow customizing Monit timeout length

---

jobs/docker/templates/bin/ctl

We discovered a problem when bosh is unmounting `/var/vcap/store`, and the `/var/vcap/store/docker/docker/overlay` is still mounted. 
`kill_and_wait` can force kill `dockerd` with `kill -9`, which leaves the `/var/vcap/store/docker/docker/overlay` fs still mounted.

Explicitly unmount overlayfs

---

jobs/docker/templates/bin/ctl

Fixes warning:
time="2018-05-01T21:41:18Z" level=warning msg="The \"-g / --graph\" flag is deprecated. Please use \"--data-root\" instead"

--data-root flag replaces --graph

---

jobs/docker/templates/bin/cgroupfs-mount
manifests/operators/add_support_for_bosh_lite.yml
manifests/operators/dev.yml

When deploying onto a bosh-lite environment using a persistent disk I am unable to execute:
```
docker run hello-world
```
However adding the extra code (_my mish-mashed understanding of configuring cgroups - apologies_) contained in the PR it executes successfully.

Add extra cgroup mounts for bosh-lite environments

---

jobs/containers/templates/bin/ctl

When using a multiline variable, the variable has unevaluated elements.
This change evaluates so that those elements are resolved.

Handle multiline environment variables correctly

---

Gemfile
Gemfile.lock
jobs/docker/templates/bin/job_properties.sh.erb
spec/docker_job_properties_spec.rb
spec/spec_helper.rb
spec/support/template_helpers.rb

Prevent variable expansion in the environment variables when there's a `$` in the URL (e.g. in the password).

Fix issues with unbound variables in HTTP and HTTPS proxy envs

---

jobs/docker/templates/bin/ctl

[#164498025](https://www.pivotaltracker.com/story/show/164498025)
PKS Flannel Network Gets Out of Sync with Docker Bridge Network (cni0)Dock
Co-authored-by: Phil Goodwin <pgoodwin@pivotal.io>
Co-authored-by: Sudhindra Rao <surao@pivotal.io>

Fixes Docker Bridge Network sync problem

---

jobs/docker/templates/bin/ctl

- since this needs to work the same way in cfcr and pks
[#164498025](https://www.pivotaltracker.com/story/show/164498025)
PKS Flannel Network Gets Out of Sync with Docker Bridge Network (cni0)Dock
Co-authored-by: Sudhindra Rao <surao@pivotal.io>
Co-authored-by: Ivan Mikushin <imikushin@vmware.com>
```release-note
Fixed the path for docker store to use the environment variable 
- since this needs to work the same way in CFCR and PKS
This fixes issue:
[#164498025](https://www.pivotaltracker.com/story/show/164498025)
PKS Flannel Network Gets Out of Sync with Docker Bridge Network (cni0)
```

Fixed the path for docker store to use the environment variable

---

jobs/docker/templates/bin/ctl

restart
- before, the docker network db was deleted after the network bridge was
created
[#164498025]

Resolve situations where docker networks fail to work after a dockerd

---

jobs/docker/monit

Increase docker stop timeout to 180 second

Docker needs more time to stop all containers
